"""initial schema

Revision ID: 1ae6a21c8536
Revises: 
Create Date: 2026-04-17 23:04:04.593065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae6a21c8536'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('search_cache',
    sa.Column('query_hash', sa.String(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('query_hash', 'source')
    )
    op.create_index(op.f('ix_search_cache_fetched_at'), 'search_cache', ['fetched_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('foco_geografico', sa.JSON(), nullable=False),
    sa.Column('clase_activo', sa.JSON(), nullable=False),
    sa.Column('subyacentes', sa.JSON(), nullable=False),
    sa.Column('comision', sa.Float(), nullable=True),
    sa.Column('comision_raw', sa.String(), nullable=True),
    sa.Column('moneda', sa.String(), nullable=True),
    sa.Column('administrador', sa.String(), nullable=True),
    sa.Column('gestor', sa.String(), nullable=True),
    sa.Column('liquidez', sa.String(), nullable=True),
    sa.Column('minimo_inversion', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_nombre'), 'products', ['nombre'], unique=False)
    op.create_table('rules_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('examples_json', sa.JSON(), nullable=True),
    sa.Column('validation_accuracy', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version', name='uq_rules_version')
    )
    op.create_table('uploaded_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extraction_result', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name_input', sa.String(), nullable=False),
    sa.Column('rules_version_id', sa.Integer(), nullable=True),
    sa.Column('classifier_output', sa.JSON(), nullable=False),
    sa.Column('reviewer_output', sa.JSON(), nullable=True),
    sa.Column('global_confidence', sa.Float(), nullable=True),
    sa.Column('per_attribute_confidence', sa.JSON(), nullable=True),
    sa.Column('final_status', sa.String(), nullable=False),
    sa.Column('source_used', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rules_version_id'], ['rules_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_product_name_input'), 'classifications', ['product_name_input'], unique=False)
    op.create_table('training_set',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('validation_set',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('human_decision', sa.String(), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.Column('final_product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['final_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_classification_id'), 'review_queue', ['classification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_classification_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_table('validation_set')
    op.drop_table('training_set')
    op.drop_index(op.f('ix_classifications_product_name_input'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_table('uploaded_documents')
    op.drop_table('rules_versions')
    op.drop_index(op.f('ix_products_nombre'), table_name='products')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_index(op.f('ix_search_cache_fetched_at'), table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
