"""add source traceability columns

Revision ID: 25b9a21f55ac
Revises: f8c8669b83a7
Create Date: 2026-05-03 14:07:33.981923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b9a21f55ac'
down_revision: Union[str, Sequence[str], None] = 'f8c8669b83a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('sources_used', sa.JSON(), nullable=True))
    op.add_column('classifications', sa.Column('field_conflicts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifications', 'field_conflicts')
    op.drop_column('classifications', 'sources_used')
    # ### end Alembic commands ###
