"""add two-layer classification columns to products

Revision ID: d2c3476dee07
Revises: 25b9a21f55ac
Create Date: 2026-05-03 23:24:55.511636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c3476dee07'
down_revision: Union[str, Sequence[str], None] = '25b9a21f55ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('administrador_producto', sa.String(), nullable=True))
    op.add_column('products', sa.Column('gestor_producto', sa.String(), nullable=True))
    op.add_column('products', sa.Column('comision_producto', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('minimo_inversion_producto', sa.String(), nullable=True))
    op.add_column('products', sa.Column('liquidez_producto', sa.String(), nullable=True))
    op.add_column('products', sa.Column('intermediario', sa.String(), nullable=True))
    op.add_column('products', sa.Column('tipo_intermediario', sa.String(), nullable=True))
    op.add_column('products', sa.Column('comision_distribucion', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('minimo_via_intermediario', sa.String(), nullable=True))
    op.add_column('products', sa.Column('liquidez_via_intermediario', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'liquidez_via_intermediario')
    op.drop_column('products', 'minimo_via_intermediario')
    op.drop_column('products', 'comision_distribucion')
    op.drop_column('products', 'tipo_intermediario')
    op.drop_column('products', 'intermediario')
    op.drop_column('products', 'liquidez_producto')
    op.drop_column('products', 'minimo_inversion_producto')
    op.drop_column('products', 'comision_producto')
    op.drop_column('products', 'gestor_producto')
    op.drop_column('products', 'administrador_producto')
    # ### end Alembic commands ###
