"""add job_queue table

Revision ID: f8c8669b83a7
Revises: 1ae6a21c8536
Create Date: 2026-04-20 10:13:54.177333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c8669b83a7'
down_revision: Union[str, Sequence[str], None] = '1ae6a21c8536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_queue_batch_id'), 'job_queue', ['batch_id'], unique=False)
    op.create_index(op.f('ix_job_queue_nombre'), 'job_queue', ['nombre'], unique=False)
    op.create_index(op.f('ix_job_queue_status'), 'job_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_queue_status'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_nombre'), table_name='job_queue')
    op.drop_index(op.f('ix_job_queue_batch_id'), table_name='job_queue')
    op.drop_table('job_queue')
    # ### end Alembic commands ###
